version: "3"

services:
  web:
    build: .
    depends_on:
      -  db
    ports:
      - 8000:8000
    volumes:
      - .:/web
      - packages:/usr/local/lib/python3.10/site-packages
      - bin:/usr/local/bin
          
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5124:5432
    environment:
      - POSTGRES_USER=sharecipe
      - POSTGRES_PASSWORD=sharecipe

volumes:
  db-volume:
  packages:
  bin: