INGREDIENTS = [
    ("carrot", "carrot"),
    ("onion", "onion"),
    ("potato", "potato"),
    ("tomato", "tomato"),
    ("brocoli", "brocoli"),
    ("mushroom", "mushroom"),
    ("garlic", "garlic"),
    ("leek", "leek"),
    ("cabbage", "cabbage"),
    ("bean", "bean"),
    ("kimchi", "kimchi"),
    ("egg", "egg"),
    ("beef", "beef"),
    ("chicken", "chicken"),
    ("pork", "pork"),
    ("fish", "fish"),
    ("sausage", "sausage"),
    ("salt", "salt"),
    ("sugar", "sugar"),
    ("vinegar", "vinegar"),
    ("soysauce", "soy sauce"),
    ("oil", "oil"),
    ("pepper", "pepper"),
    ("noodle", "noodle"),
    ("rice", "rice"),
    ("bread", "bread"),
    ("flour", "flour"),
    ("water", "water"),
    ("milk", "milk"),
    ("cheese", "cheese"),
]

THEMES = [
    ("party", "party"),
    ("meal", "meal"),
    ("entertainment", "entertainment"),
    ("nurse", "nurse"),
    ("snack", "snack"),
    ("supper", "supper"),
    ("exercise", "exercise"),
    ("diet", "diet"),
]

METHODS = [
    ("boil", "boil"),
    ("roast", "roast"),
    ("steam", "steam"),
    ("fry", "fry"),
    ("bake", "bake"),
    ("dry", "dry"),
    ("torch", "torch"),
    ("freeze", "freeze"),
]
